### ISSUE TITLE
Add functions for all supported opcodes

### ISSUE THREAD

**Issue by Kujawadl** [Kujawadl/CSC_341_OS_Lab#1]
Opcodes:
- [x] LOD
- [x] STO
- [x] ADD
- [x] SUB
- [x] ADR
- [x] SUR
- [x] AND
- [x] IOR
- [x] NOT
- [x] JMP
- [x] JEQ **
- [x] JGT **
- [x] JLT **
- [x] CMP
- [x] CLR
- [x] HLT

**Comment by Kujawadl** [comment]
Please note the TODO comments in the machine.c file, concerning the ~~math~~<sup>1</sup> ~~and~~ jump functions. I'd love your feedback to determine if I've interpreted the handout correctly. We may need to go to Dr. Strader.

Also consider the following:
- **What should CMP compare?** I propose it compare a non-special register (r1-r3) with either a direct or an immediate operand, and then store the result (see the `#define`s at the top of machine.h for comparison return values) in rA. Thoughts?
- **Do we know what CLR should do?**
- **What is the behavior of HLT?** Should it simply clear all the registers? How is the operating system notified of the HLT? What do you think?

> <sup>1</sup>The math TODO comments were entirely about checking for integer overflow. At first I considered looking up overflow checking in the 214 book or seeing if there's a macro online for this, but then I realized: we're only using 16-bit integers. All we have to do to check for overflow is cast the operands into 32-bit integers, perform the same operation with said duplicates, and then compare the results. If an integer overflow occurs, then the 16-bit result won't match the 32-bit result, because the 32-bit result wouldn't have the same overflow problems.

**Comment by AndrewGBallard** [comment]
**HLT** should crash the computer, and I believe that **CLR** simply takes a specific register and wipes that to an all 0 state. Though, I'm sure we can make a functionality to clear all registers if we need one, but we can talk to Strader about that later.
