### ISSUE TITLE
Semaphore must be implemented

### ISSUE THREAD

**Issue by Kujawadl** [Kujawadl/CSC_341_OS_Lab#19]
### The semaphore must be implemented as follows:
- A binary semaphore [global boolean value defined in os.hpp (`extern bool semaphore;`) and declared in os.cpp (`bool semaphore = false; // Default value is unlocked`)].
- When a user issues `run` at the command line, the `bool semwait()` method is immediately called, the output of which determines if a swap has occurred and thus, if execution should continue. If a swap has occurred (i.e.: the current user was moved to the blockedQueue) the scheduler should output that information to the command line and reset `switchtime = sysclock + 3` _(because the dispatcher was called in the semwait() function, and thus we now have a new currentUser. Execution must continue within the `while (sysclock < switchtime)...` loop, because if we were to break from this loop and start the scheduler from its initial loop, the dispatcher would be called a second time, skipping a user. Thus, rather than shortening the life of the loop or breaking, we extend the life of the loop such that it will repeat for three more ticks.)_
- When the user's program encounters a halt (opcode 15, i.e.: IR code 61440), the `semsignal()` method is called, then the dispatcher is immediately called to switch to the next user.
- The dispatcher must be modified to take in a parameter indicating a signal it is receiving. This signal will be used to determine whether the current user is blocked or ready so the dispatcher can decide which queue to place them in on switch.

Algorithms:

```
dispatcher(int signal)
  - Save machine registers into currentUser (save user state)
  - If signal is BLOCKED (arbitrarily defined as some int), push currentUser onto blockedQueue
  - Else if signal is READY (arbitrarily defined as some int), push currentUser onto readyQueue
  - Set currentUser to readyQueue.front; pop front of readyQueue (get next user)
  - Set machine registers to currentUser.regs (load user state)

semwait()
  - If semaphore is unlocked, lock it and return true, indicating that the current user is OK to 
    run.
  - If semaphore is locked, call dispatcher with blocking signal, indicating that the dispatcher 
    should place the current user in the blockedQueue, rather than the default readyQueue. 
    The dispatcher will then load the next user from the readyQueue. Return false, indicating 
    that the user has been sent to the blocked queue, and the run statement should not 
    continue to call the interpreter.

semsignal()
  - If semaphore is locked, unlock it and move all items in blockedQueue into readyQueue.
  - semsignal() should not be called unless the semaphore is locked, as this method indicates 
    that the semaphore is ready to be unlocked and all users waiting on the semaphore should 
    be moved to ready status.
```

**Comment by AndrewGBallard** [comment]
Okay, on both semwait and semsignal now, Dispatcher is done... sort of. It saves registers to proper user, but it does not ever deal with the blocked queue. The users in the blocked queue will eventually be sent back into the ready queue, thus they will eventually be put back in queue. I guess I could throw something together in a bit, but for now I am moving on.

**Comment by AndrewGBallard** [comment]
Done I think, we really need to start verification.
