### ISSUE TITLE
dmp() must dump all user registers

### ISSUE THREAD

**Issue by Kujawadl** [Kujawadl/CSC_341_OS_Lab#20]
We lost points on this last time. Turn debug off (`#undef DEBUG`) and add code to the dmp function to traverse the process queues (CHECK IF EMPTY TO AVOID NULLREF) and print out each user's registers, plus the machine registers.

**Comment by AndrewGBallard** [comment]
I'm on it nerd!

**Comment by AndrewGBallard** [comment]
Okay, this is essentially done, but not completely. I assume that this needs to indicate what user is blocked, so we need the seramophone.... Seraphone? The thing...

**Comment by Kujawadl** [comment]
Pull Request #24 - Implemented
Commit [f5178cb](https://github.com/Kujawadl/CSC_341_OS_Lab/commit/ccf04ce60faa63ba3a398d992d472dc17f3570a8) - Finalized
