### ISSUE TITLE
Rewrite readfile()

### ISSUE THREAD

**Issue by Kujawadl** [Kujawadl/CSC_341_OS_Lab#21]
Readfile should use C++ streams (mixing streams with old c fputs and fgets causes problems).

Readfile should take a filename and a starting address, the load the specified file into memory at the specified address. Be sure to check for IndexOutOfBounds.

The init() function should then be modified so it calls `readfile("part1.dat", 0); readfile("part2.dat", 100);` or something to that effect. It should also set the PC of U1 and U2 to 0 and 100, respectively.

**Comment by AndrewGBallard** [comment]
Just got this done.

**Comment by baker12** [comment]
Semaphore is the word you're thinking of :)

**Comment by AndrewGBallard** [comment]
WRONG THREAD BITCH

**Comment by baker12** [comment]
Whoops!

**Comment by Kujawadl** [comment]
lol
