### ISSUE TITLE
Some #include statements commented out

### ISSUE THREAD

**Issue by baker12** [Kujawadl/CSC_341_OS_Lab#25]
In os.hpp we have

`//Needed for formatting when printing
//</stdio.h></stdlib.h></string.h>`

Do we need that commented out?

**Comment by Kujawadl** [comment]
Yes. The gh-pages branch that generates our report for printing needs that.

Basically, it reads the raw source from the main repo, puts it into a
<code></code> block, and then uses javascript to highlight the syntax. For
some reason, the syntax highlighter refuses to see <stdio.h> as C code, and
instead only sees it as an html tag, and then tries to place a
corresponding </stdio.h> tag at the end when it doesn’t find one, in an
attempt to “fix” the faulty html. Those end tags show up at the bottom of
the file, highlighted as C code. It’s real dumb.

Placing that line there satisfies the angry god that is SyntaxHighlighter.js

Although the lines will likely need to be updated, as our includes have
changed.

**Comment by baker12** [comment]
Do I need to leave them as // or do I change those to /\* */ as well?

**Comment by Kujawadl** [comment]
I’ll change those, don’t worry about it. The gh-pages thing is a little
wonky sometimes lol
