### ISSUE TITLE
Overflow in SUR()

### ISSUE THREAD

**Issue by Kujawadl** [Kujawadl/CSC_341_OS_Lab#61]
User 2 process, instruction 4:
SUR 0 r1 0

Overflow causes error condition which halts process early.

This may be intentional or it may be a bug, but it needs to be looked into ASAP.

**Comment by AndrewGBallard** [comment]
Okay, I've been staring at this for a while, and I think it's come down to the fact that I am unsure on the logic that is checking to see if overflow occured, what exactly is happening here:
https://i.imgur.com/MIDRmyD.png

**Comment by Kujawadl** [comment]
So basically it converts the memory content from a 16 bit short into a 33
bit int, and reperforms the calculation. If there is overflow or underflow,
the interest and short calcs shouldn't match.

E.g.:

(unsigned short) 65535 + 1 = 0
(int)65536 + 1 = 65536

Also:
(unsigned short) 0 -  1 = 65535
(int)0 - 1 = - 1

**Comment by Kujawadl** [comment]
So the value in R1 is 5, and the command in question is subtracting 0 (memory address 0 or literal value 0? idk) but I don't think it should have an underflow condition, and I think he's going to count off for that...

**Comment by Kujawadl** [comment]
This really needs to be a priority this time around. We got lucky he didn't notice last time, but that was probably only because he didn't bother reading the output :/

We can't count on being lucky like that again
